### ISSUE TITLE
EPIC: Mailbox - Cosmos SDK module

### ISSUE THREAD

**Issue by misko9** [strangelove-ventures/hyperlane-cosmos#2]
```[tasklist]
- [x] https://github.com/strangelove-ventures/hyperlane-cosmos/issues/10
- [x] https://github.com/strangelove-ventures/hyperlane-cosmos/issues/11
- [ ] https://github.com/strangelove-ventures/hyperlane-cosmos/issues/12
- [ ] https://github.com/strangelove-ventures/hyperlane-cosmos/issues/18
- [x] #26
- [x] #25
```
