### ISSUE TITLE
EPIC: MultisigISM - Cosmos SDK module

### ISSUE THREAD

**Issue by misko9** [strangelove-ventures/hyperlane-cosmos#4]
```[tasklist]
- [x] Scaffold hyperlane sdk module https://github.com/strangelove-ventures/hyperlane-cosmos/issues/10
- [x] Add basic simapp with hyperlane sdk module https://github.com/strangelove-ventures/hyperlane-cosmos/issues/11
- [x] Add hyperlane-simd to heighliner https://github.com/strangelove-ventures/hyperlane-cosmos/issues/12
- [x] ISM: implement and unit test verify method with IMT https://github.com/strangelove-ventures/hyperlane-cosmos/issues/20
- [x] hyperlane-simd: add to interchaintest to for cli tx/query single chain testing https://github.com/strangelove-ventures/hyperlane-cosmos/issues/21
- [ ] #32
```

**Comment by Olshansk** [comment]
@jonathanpberger Do you think this module could be used for multi-sig addresses within an ABCI application outside of hyperplane?

I can provide a lot more details on the context for my ask ([example](https://github.com/pokt-network/poktroll/issues/322)), but I am intentionally trying to keep this ask short.

Thanks in advance!
