### ISSUE TITLE
IGP: Cosmos <-> Cosmos e2e test in interchaintest

### ISSUE THREAD

**Issue by KyleMoser** [strangelove-ventures/hyperlane-cosmos#49]
Implement a test case that sets up an IGP, oracle, and gas prices/overhead, then manually relays it to a destination. This will confirm that the RPC queries for dispatch and payForGas work properly. 

- This will not use a "real" validator, it will manually sign.
- In the future this will evolve into a full e2e test using the real validator

```[tasklist]
### Tasks
- [ ] https://github.com/strangelove-ventures/hyperlane-cosmos/issues/64
- [ ] https://github.com/strangelove-ventures/hyperlane-cosmos/issues/63
- [ ] https://github.com/strangelove-ventures/hyperlane-cosmos/issues/62
- [ ] https://github.com/strangelove-ventures/hyperlane-cosmos/issues/65
- [ ] https://github.com/strangelove-ventures/hyperlane-cosmos/issues/66
```

**Comment by akc2267** [comment]
@misko9 to prep docker image and put it in heighliner

**Comment by akc2267** [comment]
tbd: how to mock the relayer and validator so its not needed for this test

**Comment by akc2267** [comment]
https://github.com/strangelove-ventures/heighliner-build-action

^ example from Noble
