### ISSUE TITLE
EPIC: InterchainGasPaymaster - Cosmos SDK module

### ISSUE THREAD

**Issue by misko9** [strangelove-ventures/hyperlane-cosmos#5]
```[tasklist]
- [ ] #10 
- [ ] #11 
- [ ] #12 
- [ ] https://github.com/strangelove-ventures/hyperlane-cosmos/issues/28
- [ ] https://github.com/strangelove-ventures/hyperlane-cosmos/issues/43
- [ ] https://github.com/strangelove-ventures/hyperlane-cosmos/issues/44
- [ ] https://github.com/strangelove-ventures/hyperlane-cosmos/issues/49
```
