### ISSUE TITLE
EPIC: Announcement module

### ISSUE THREAD

**Issue by KyleMoser** [strangelove-ventures/hyperlane-cosmos#77]
Write announcement module for SDK
```[tasklist]
### Tasks
- [ ] https://github.com/strangelove-ventures/hyperlane-cosmos/issues/82
- [ ] https://github.com/strangelove-ventures/hyperlane-cosmos/issues/81
- [ ] https://github.com/strangelove-ventures/hyperlane-cosmos/issues/80
- [ ] https://github.com/strangelove-ventures/hyperlane-cosmos/issues/79
- [ ] https://github.com/strangelove-ventures/hyperlane-cosmos/issues/78
```
