### ISSUE TITLE
EPIC: Hyperlane Validator - Cosmos SDK module support

### ISSUE THREAD

**Issue by misko9** [strangelove-ventures/hyperlane-cosmos#8]
The validator will be integrated into the mono repo here: https://github.com/hyperlane-xyz/hyperlane-monorepo/tree/main

```[tasklist]
### Tasks
- [ ] https://github.com/strangelove-ventures/hyperlane-cosmos/issues/51
- [ ] https://github.com/strangelove-ventures/hyperlane-cosmos/issues/52
- [ ] https://github.com/strangelove-ventures/hyperlane-cosmos/issues/53
- [ ] https://github.com/strangelove-ventures/hyperlane-cosmos/issues/54
```

**Comment by jonathanpberger** [comment]
This ougtta be like the relayer, but simpler. Query chain, sign it, post sig to S3 bucket. Easy peasy.

**Comment by misko9** [comment]
MVP validator agent has been tested. Next step is to integrate validator announce and test.

**Comment by jonathanpberger** [comment]
> Next step is to integrate validator announce and test.

Great! Please either 1) close out this ticket, or 2) add DoD for the remaining work in the Tasklist. TY!
